USE wave_friend;

CREATE TABLE bonds (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    user1_id INTEGER NOT NULL,
    user2_id INTEGER NOT NULL,
    bonded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user1_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (user2_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
); 